---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by alspin.
--- DateTime: 21/10/2024 13:28
---

task("plot-sd")
    set_menu {
        usage       = "xmake plot",
        description = "Plot out.txt with gnuplot",
        options     = {
            {"p", "file", "kv", "", "The file path" }
        }
    }

    on_run(function ()
        import("core.base.option")
        local file = option.get("path")
        local dir  = path.join(path.directory(file), "asset")

        if (not os.isdir(dir)) then
            os.mkdir(dir)
        end

        os.exec("gnuplot -e \"set terminal png; set output '" .. dir .. "/p.png'; plot '".. file .."' using 1:2 title 'px(t)' with lines, '".. file .."' using 1:3 title 'py(t)' with lines, '".. file .."' using 1:4 title 'pz(t)' with lines;\"")
        os.exec("gnuplot -e \"set terminal png; set output '" .. dir .. "/v.png'; plot '".. file .."' using 1:5 title 'vx(t)' with lines, '".. file .."' using 1:6 title 'vy(t)' with lines, '".. file .."' using 1:7 title 'vz(t)' with lines;\"")
        os.exec("gnuplot -e \"set terminal png; set output '" .. dir .. "/a.png'; plot '".. file .."' using 1:8 title 'ax(t)' with lines, '".. file .."' using 1:9 title 'ay(t)' with lines, '".. file .."' using 1:10 title 'az(t)' with lines;\"")
    end)